# Default application configuration that all configurations inherit from.
linters:
    BorderZero:
        # Prefer border: 0 over border: none.
        enabled: true

    CapitalizationInSelector:
        # IDs, classes, types, placeholders, and pseudo-selectors should be all
        # lowercase.
        enabled: true

    ColorKeyword:
        # Prefer hexadecimal color codes over color keywords.
        enabled: true

    Comment:
        # Prefer // comments over /* ... */.
        enabled: true

    DebugStatement:
        # Reports @debug statements (which you probably left behind
        # accidentally).
        enabled: true

    DeclarationOrder:
        # Write @extend statements first in rule sets, followed by property
        # declarations and then other nested rule sets.
        enabled: true

    DuplicateProperty:
        # Reports when you define the same property twice in a single rule set.
        enabled: false

    EmptyLineBetweenBlocks:
        # Separate rule, function, and mixin declarations with empty lines.
        enabled: true
        ignore_single_line_blocks: false

    EmptyRule:
        # Reports when you have an empty rule set.
        enabled: true

    FinalNewline:
        # Files should always have a final newline. This results in better
        # diffs when adding lines to the file, since SCM systems such as git
        # won't think that you touched the last line.
        enabled: true
        present: true

    HexFormat:
        # Prefer the shortest possible form for hexadecimal color codes.
        enabled: false # WE CAN USE THE 'LONG' FORMAT

    IdWithExtraneousSelector:
        # Don't combine additional selectors with an ID selector.
        enabled: true

    Indentation:
        # Use two spaces per indentation level. No hard tabs
        enabled: false # WE USE HARD TABS
        width: 4

    LeadingZero:
        # Don't write leading zeros for numeric values with a decimal point.
        enabled: true
        style: include_zero # or 'exclude_zero'

    MergeableSelector:
        # Reports when you define the same selector twice in a single sheet.
        enabled: true
        force_nesting: true

    NameFormat:
        # Functions, mixins, and variables should be declared with all lowercase
        # letters and hyphens instead of underscores.
        enabled: true
        convention: hyphenated_lowercase # or 'BEM', or a regex pattern

    PlaceholderInExtend:
        # Always use placeholder selectors in @extend.
        enabled: false #WE PROBABLY WANT TO USE A CLASS TOO...

    PropertySortOrder:
        # Sort properties in a strict order. By default, will require properties
        # be sorted in alphabetical order
        enabled: false # WE SHOULD PROVIDE AN OWN RULESET USING THE 'order' PROP

    PropertySpelling:
        # Reports when you use an unknown CSS property (ignoring vendor-prefixed
        # properties).
        enabled: false # WE ARE LAZY AND DON'T WANT TO TO LIST EXTRA
                       # EXPERIMENTAL PROPERTIES
        extra_properties: []

    SelectorDepth:
        # Don't write selectors with a depth of applicability greater than 3.
        enabled: true
        max_depth: 4

    Shorthand:
        # Prefer the shortest shorthand form possible for properties that
        # support it.
        enabled: true

    SingleLinePerSelector:
        # Split selectors onto separate lines after each comma.
        enabled: true

    SpaceAfterComma:
        # Commas in lists should be followed by a space.
        enabled: true

    SpaceAfterPropertyColon:
        # Properties should be formatted with a single space separating the
        # colon from the property's value.
        enabled: true

    SpaceAfterPropertyName:
        # Properties should be formatted with no space between the name and
        # the colon.
        enabled: true

    SpaceBeforeBrace:
        # Opening braces should be preceded by a single space.
        enabled: true
        allow_single_line_padding: false

    SpaceBetweenParens:
        # false
        enabled: true
        spaces: 0

    StringQuotes:
        # String literals should be written with single quotes unless using
        # double quotes would save on escape characters.
        enabled: true
        style: double_quotes # or single_quotes

    TrailingSemicolonAfterPropertyValue:
        # Property values should always end with a semicolon.
        enabled: true

    UnnecessaryMantissa:
        # Numeric values should not contain unnecessary fractional portions.
        enabled: false

    UrlFormat:
        # URLs should not contain protocols or domain names.
        enabled: false # WE PROBABLY WANT TO USE PROTOCOL AND DOMAIN

    UrlQuotes:
        # URLs should always be enclosed within quotes.
        enabled: true

    ZeroUnit:
        # Omit length units on zero values.
        enabled: true

    Compass::*:
        enabled: false